#! /bin/bash

cd ~/Desktop

git clone https://github.com/snlo/SNWorkflow.git

#clear
rm -rf ~/Library/Developer/Xcode/Templates/File\ Templates/Snlo\ Source

#copy
cp -rf ~/Desktop/SNWorkflow/SNWorkflow/Snlo\ Source ~/Library/Developer/Xcode/Templates/File\ Templates

#clear
rm -rf ~/Desktop/SNWorkflow

echo '设置最新的文件模板。。。成功'


